# +----------------------------------------------------------------------------------------+ #
# + CPU Config File.                                                                         #
# + Check out the project page at http://dev.bukkit.org/bukkit-plugins/cpu/ for more info    #
# + File will reset if you did something wrong                                               #
# + And please do not touch the ModuleDatabase.yml at all cost!
# +----------------------------------------------------------------------------------------+ #
disabled: false
send-info: true
notify-updates: true